---
title: "Ana KNN"
author: "Athilah Ahmad"
date: "4/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Data Cleaning
```{r}
pet <- read.csv("train.csv")
pet$Name <- NULL
pet$State <- NULL
pet$RescuerID <- NULL
pet$Description <- NULL
pet$PetID <- NULL

pet$Type <- as.factor(pet$Type)
pet$Breed1 <- as.factor(pet$Breed1)
pet$Gender <- as.factor(pet$Gender)
pet$MaturitySize <- as.factor(pet$MaturitySize)
pet$FurLength <- as.factor(pet$FurLength)
pet$Vaccinated <- as.factor(pet$Vaccinated)
pet$Dewormed <- as.factor(pet$Dewormed)
pet$Sterilized <- as.factor(pet$Sterilized)
pet$Health <- as.factor(pet$Health)
pet$AdoptionSpeed<- as.factor(pet$AdoptionSpeed)


pet$mixedbreed <- ifelse(pet$Breed2 == 0, 0,1)
pet$Breed2 <- NULL
pet$mixedbreed <- as.factor(pet$mixedbreed)
str(pet)

```



```{r}
set.seed(3)
trainid <- sample(1:nrow(pet), .8*nrow(pet))
train <- pet[trainid,]
test <- pet[-trainid,]
train_labels <- train$AdoptionSpeed
test_labels <- test$AdoptionSpeed
```


```{r}
library(class)
test_pred <- knn(train = train, test = test,
                      cl = train_labels, k=4)
```
```{r}
library(gmodels)
CrossTable(x = test_labels, y = test_pred, 
           prop.chisq=FALSE)
```

# Linear Regression
```{r}
accuracyrate<- mean(test_pred == test_labels)
accuracyrate
```

```{r}
pet$AdoptionSpeed<-as.numeric(pet$AdoptionSpeed)
pet$Breed1<-as.numeric(pet$Breed1)


set.seed(3)
trainid <- sample(1:nrow(pet), .8*nrow(pet))
train <- pet[trainid,]
test <- pet[-trainid,]
train_labels <- train$AdoptionSpeed
test_labels <- test$AdoptionSpeed

linReg<- lm(AdoptionSpeed ~. , data= train)
# summary(linReg)


```

```{r}
linRegResult<- predict(linReg, test)

linRegPred<-ifelse(linRegResult<2,0,
                   ifelse(linRegResult<3, 1,
                         ifelse(linRegResult<4,2,
                                ifelse(linRegResult<5,3,
                                       4))))
accuracyrate<- mean(linRegPred == test$AdoptionSpeed)
accuracyrate

```

```{r}
hh<-data.frame(
  "Actual" = test$AdoptionSpeed,
  "Predicted"= linRegPred
)

head(hh)
```






