---
title: "Project 3"
author: "Arsyad Asnawi"
date: "4/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Data Cleaning
```{r}
anndata <- read.csv("train.csv")
anndata$Name <- NULL
anndata$State <- NULL
anndata$RescuerID <- NULL
anndata$Description <- NULL
anndata$PetID <- NULL

anndata$Color1 <- as.factor(anndata$Color1)
anndata$Color2 <- as.factor(anndata$Color2)
anndata$Color3 <- as.factor(anndata$Color3)
anndata$Type <- as.factor(anndata$Type)
anndata$Breed1 <- as.factor(anndata$Breed1)
anndata$Gender <- as.factor(anndata$Gender)
anndata$MaturitySize <- as.factor(anndata$MaturitySize)
anndata$FurLength <- as.factor(anndata$FurLength)
anndata$Vaccinated <- as.factor(anndata$Vaccinated)
anndata$Dewormed <- as.factor(anndata$Dewormed)
anndata$Sterilized <- as.factor(anndata$Sterilized)
anndata$Health <- as.factor(anndata$Health)
anndata$mixedbreed <- ifelse(anndata$Breed2 == 0, 0,1)
anndata$Breed2 <- NULL
anndata$mixedbreed <- as.factor(anndata$mixedbreed)
anndata$AdoptionSpeed <- ifelse(anndata$AdoptionSpeed == 0 | anndata$AdoptionSpeed == 1 | anndata$AdoptionSpeed == 2, 0,1 )

response <- anndata$AdoptionSpeed
anndata$AdoptionSpeed <- NULL
anndata$AdoptionSpeed <- response

# str(anndata)
```

#Normalize Data
```{r}
anndata_random <- anndata[sample(nrow(anndata)), ]

normalize <- function(x) { 
  return((x - min(x)) / (max(x) - min(x)))
}

anndata_n1 <- as.data.frame(lapply(anndata_random[2], normalize))
anndata_n2 <- as.data.frame(lapply(anndata_random[14:17], normalize))

anndata_n <- data.frame(c(anndata_random[1], anndata_n1, anndata_random[3:13], anndata_n2, anndata_random[18:19]))

# str(anndata_n)
```
```{r}
anndata_mm<- as.data.frame(model.matrix(~ . -1, anndata_n))
```


```{r}
set.seed(3)
anntrainid <- sample(1:nrow(anndata_mm), .8*nrow(anndata_mm))
anntrain <- anndata_mm[anntrainid,]
anntest <- anndata_mm[-anntrainid,]
anntrain_labels <- anntrain$AdoptionSpeed
anntest_labels <- anntest$AdoptionSpeed
```

```{r}
library(neuralnet)
m1 <- neuralnet(formula = AdoptionSpeed ~ . , data = anntrain)

# plot(m1)
```

```{r}
library(class)
library(gmodels)

ann_result <- compute(m1,anntest)

predicted <- ann_result$net.result

summary(predicted)

ann_pred <- ifelse(predicted > mean(predicted) , 1, 0)

summary(anntest$AdoptionSpeed)

library(caret)

pet_cM_ann <- confusionMatrix(as.factor(ann_pred), as.factor(anntest_labels))

ann_acc <- mean(ann_pred == anntest_labels)

ann_acc

```



