---
title: "final project"
author: "Jen Lyn Chung"
date: "4/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Data Cleaning
```{r}
pet <- read.csv("train.csv")
pet$Name <- NULL
pet$State <- NULL
pet$RescuerID <- NULL
pet$Description <- NULL
pet$PetID <- NULL

pet$Type <- as.factor(pet$Type)
pet$Breed1 <- as.factor(pet$Breed1)
pet$Gender <- as.factor(pet$Gender)
pet$MaturitySize <- as.factor(pet$MaturitySize)
pet$FurLength <- as.factor(pet$FurLength)
pet$Vaccinated <- as.factor(pet$Vaccinated)
pet$Dewormed <- as.factor(pet$Dewormed)
pet$Sterilized <- as.factor(pet$Sterilized)
pet$Health <- as.factor(pet$Health)


pet$mixedbreed <- ifelse(pet$Breed2 == 0, 0,1)
pet$Breed2 <- NULL
pet$mixedbreed <- as.factor(pet$mixedbreed)
str(pet)

```

#Normalize Data
```{r}

pet$AdoptionSpeed <- ifelse(pet$AdoptionSpeed == 0 | pet$AdoptionSpeed == 1 | pet$AdoptionSpeed == 2, 0,1 )
pet_random <- pet[sample(nrow(pet)), ]

normalize <- function(x) { 
  return((x - min(x)) / (max(x) - min(x)))
}

pet$AdoptionSpeed <- as.factor(pet$AdoptionSpeed)
pet$AdoptSpeed <- pet$AdoptionSpeed
pet$AdoptionSpeed <- NULL

library(dummies)
pet_dummy <- dummy.data.frame(data = pet[,-ncol(pet)],)

pet_norm <- as.data.frame(lapply(pet_dummy, normalize))
pet_norm$AdoptionSpeed <- pet$AdoptSpeed
```


```{r}
set.seed(3)
trainid <- sample(1:nrow(pet_norm), .8*nrow(pet_norm))
train <- pet_norm[trainid,]
test <- pet_norm[-trainid,]
train_labels <- train$AdoptionSpeed
test_labels <- test$AdoptionSpeed
```


#SVM Model
```{r}
pet_classifier_rbf <- ksvm(AdoptionSpeed ~ Type1 + Type2 + MaturitySize1 + MaturitySize2 + MaturitySize3 + MaturitySize4 + FurLength1 + FurLength2 + FurLength3 + Vaccinated1 + Vaccinated2 + Vaccinated3 + Dewormed1 + Dewormed2 + Dewormed3 + Sterilized1 + Sterilized2 + Sterilized3 + Health1 + Health2 + Health3 + Quantity + PhotoAmt + mixedbreed0 + mixedbreed1, data = train, kernel = "rbfdot")

svm_pred <- predict(pet_classifier_rbf, test)

agreement_rbf <- svm_pred == test$AdoptionSpeed
table(agreement_rbf)
prop.table(table(agreement_rbf))

svm_acc<- mean(svm_pred == test$AdoptionSpeed)
svm_acc


```

#Analysis

We checked all the affecting variables and substituted the breed factor with mixed breed factor. After building two SVM Models (one with vanilladot, one with rbfdot), we discovered that the rbfdot possessed higher accuracy. Hence we chose rbfdot SVM model for our prediction. 


