---
title: "Report"
author: "Yunjia Xu"
date: "3/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background

## Data
```{r}
pet <- read.csv("train.csv")
pet$Name <- NULL
pet$State <- NULL
pet$RescuerID <- NULL
pet$Description <- NULL
pet$PetID <- NULL

pet$Type <- as.factor(pet$Type)
pet$Breed1 <- as.factor(pet$Breed1)
pet$Gender <- as.factor(pet$Gender)
pet$MaturitySize <- as.factor(pet$MaturitySize)
pet$FurLength <- as.factor(pet$FurLength)
pet$Vaccinated <- as.factor(pet$Vaccinated)
pet$Dewormed <- as.factor(pet$Dewormed)
pet$Sterilized <- as.factor(pet$Sterilized)
pet$Health <- as.factor(pet$Health)


pet$mixedbreed <- ifelse(pet$Breed2 == 0, 0,1)
pet$Breed2 <- NULL
pet$mixedbreed <- as.factor(pet$mixedbreed)
str(pet)


```

## Regression model
```{r}
lmodel <- lm( AdoptionSpeed ~. , data = pet)
summary(lmodel)

lmodel2 <- lm( AdoptionSpeed ~ Type + Age + Gender + Color1 + Color2 + Color3 + MaturitySize + FurLength + Vaccinated + Dewormed + Sterilized + Health + Quantity + PhotoAmt + mixedbreed , data = pet)
summary(lmodel2)
```

## Prediction model

```{r}
set.seed(3)
trainid <- sample(1:nrow(pet), .8*nrow(pet))
train <- pet[trainid,]
test <- pet[-trainid,]
train_labels <- train$AdoptionSpeed
test_labels <- test$AdoptionSpeed
```

```{r}
library(class)
test_pred <- knn(train = train, test = test,
                      cl = train_labels, k=21)
library(gmodels)
CrossTable(x = test_labels, y = test_pred, 
           prop.chisq=FALSE)
```


### Bagging

```{r}
pet$AdoptionSpeed <- as.factor(pet$AdoptionSpeed)
# Using the ipred bagged decision trees
library(ipred)
set.seed(300)
mybag <- bagging(AdoptionSpeed ~ ., data = pet, nbagg = 25)
pet_pred <- predict(mybag, pet)
table(pet_pred, pet$AdoptionSpeed)

# estimate performance of ipred bagged trees
library(caret)
set.seed(300)
ctrl <- trainControl(method = "cv", number = 10)
train(AdoptionSpeed ~ ., data = pet, method = "treebag",
      trControl = ctrl)
```


## Conclusion
